# Github Actions: Build

## description:
##   Test Dockerfile

name: Docker Image CI

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${image_name}:$(date +%s)
        env:
          image_name: ${{ github.registory }}
